### ISSUE TITLE
Factor out SPV client

### ISSUE THREAD

**Issue by mvayngrib** [throughnothing/BitcoinSPVCrx#3]
very happy to see an SPV client in JS!

It'd be easier for people to contribute if this was split up into several modules: 
1. SPV client
2. wallet (depends on spv client)
3. chrome app (depends on wallet)

**Comment by throughnothing** [comment]
Hey @mvayngrib thanks, I was thinking about that, and I think it can be split out pretty easily.  I"m not sure if the wallet would need to depend on the SPV client, per se, but could be a HD wallet that could be used to generate addresses and sign TX, without needing SPV (if someone wanted to just use it with chain or blockchain.info API's for example).

Then the Chrome App could depend on the wallet and the spv client.  This would make it also easy to build a firefox app, etc..

**Comment by throughnothing** [comment]
Also, if you haven't seen [bcoin](https://github.com/indutny/bcoin), you should check it out.  I've taken a lot of ideas from there, but I wanted this one to be based on bitcore, rather than re-implementing all the primitives from scratch, as I think long-term bitcore will get more bug fixes and support since it has BitPay behind it.

**Comment by mvayngrib** [comment]
That sounds good. Yea, I've seen bcoin, and had exactly the same problem with it: it reimplements everything. @indutny is a star though. 

I work with bitcoinjs-lib mostly, so it makes me a little sad to see you use bitcore. I realize bitcoinjs-lib doesn't have the p2p code though.

**Comment by throughnothing** [comment]
@mvayngrib yeah, I looked at bitcoinjs-lib as well as @ryanxcharles' [fullnode](https://github.com/ryanxcharles/fullnode), but I think bitcore has the best bet of long-term maintenance right now, and I don't want to be maintaining the core bitcoin primitives myself as we get new features/BIP's introduced over time.

I'm also working now to split the SPV + Wallet out into [bitcore-spv](https://github.com/throughnothing/bitcore-spv).  I think you're right in that hopefully by splitting them out into smaller, more logical pieces I can get more help and PR's :)

For now, I think it may be hard to separate the wallet from the SPV node, so I'm going to put both in one repo/package and see if it makes sense to split the wallet out later on.

**Comment by throughnothing** [comment]
Ok, broke the SPV stuff out to [bitcore-spv](https://github.com/throughnothing/bitcore-spv) and removed it from this repo to require that lib.

I think that's a great start for now.  And the `bitcore-spv` repo doesn't need to require any of the chrome stuff or webpack/bootstrap/loaders.  Good call :)

**Comment by mvayngrib** [comment]
awesome, looking forward to playing around with bitcore-spv :)

**Comment by throughnothing** [comment]
@mvayngrib awesome! :)  Currently, in order to be able to watch addresses in the SPV client, I need bloom filters, which are not fully supported in `bitcore` yet.  I have some upstream work to do in `bitcore` and `bitcore-p2p` which can be seen here:

**Already Done**
- https://github.com/bitpay/bitcore-p2p/pull/40
- https://github.com/bitpay/bitcore-p2p/pull/39

**In Progress**
- https://github.com/bitpay/bitcore/pull/1102
- https://github.com/bitpay/bitcore-p2p/pull/43

That's the next place I'm working on for right now.

**Comment by ryanxcharles** [comment]
Awesome work. Agreed that bitcore probably has the best bet of continued maintenance. With that being said, I do intend to keep working on fullnode until SPV and an actual full node is complete. But it might take longer.

**Comment by throughnothing** [comment]
@ryanxcharles yeah, I definitely hope there will be multiple well-maintained implementations.  I'm planning to keep monitoring your progress on fullnode as well.

**Comment by mvayngrib** [comment]
there's also [cryptocoinjs](https://github.com/cryptocoinjs), which would be great to get more people working on, as it's not monolithic like bitcoinjs-lib and bitcore.

**Comment by throughnothing** [comment]
Bitcore isn't very monolithic anymore.  They're splitting it up into smaller modules.  Is that what you mean?

**Comment by mvayngrib** [comment]
They are I guess, I see bitcore-p2p and bitcore-node and a couple of others, but it's very monolithic compared to cryptocoinjs or if you take a look at @feross bittorrent modules

Edit: don't get me wrong, I'm very happy bitcore and bitcoinjs-lib exist and are so actively evolved
